### ISSUE TITLE
insecure random

### ISSUE THREAD

**Issue by socketpair** [pipobscure/otp#13]
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey

should be used instead of `Math.random()`

**Comment by pipobscure** [comment]
You are making assertions here that while echoed by many are not really relevant in context.

`Math.random` is considered insecure because it does not have sufficient entropy to generate truly random numbers. This can be exploited by an attacker if they can observe the key-generation.

However the *key* generated here isn't a cryptographic key in the common sense. So the rules regarding that are out the window. Especially since this is a shared *secret* rather than a *key*. In short, the issue you mention is entirely irrelevant to the situation here.

Any case now that mys SOC has `getRandomValues` I am happy to just use that since it's more ergonomic anyhow.
